### ISSUE TITLE
Livedoc UI throws client-side exception when no flows exist

### ISSUE THREAD

**Issue by jpeffer** [joffrey-bion/livedoc#103] opened 2018-05-03 20:51 UTC
Livedoc UI throws client-side exception when no flows exist. Below is a screenshot of the exception that occured:

![livedoc flows exception](https://user-images.githubusercontent.com/1865672/39602114-32b0b5b4-4ef2-11e8-98d5-d152ff952c8e.png)

**Comment by joffrey-bion** [comment] 2018-05-04 14:36
I cannot reproduce this issue with Livedoc 4.4.1.
The absence of flows doesn't break anything when I try to reproduce, I happen to have a "Flows" tab, and it leads to a page with no flows, but working fine.

Could you please make sure you are using the same version of Livedoc in the UI and the backend, and maybe try clearing your local storage?

This should not be necessary anymore in later versions of Livedoc, as they will check the version in the local storage data and fetched data.

**Comment by joffrey-bion** [comment] 2018-05-04 19:23
Closing as duplicate of https://github.com/joffrey-bion/livedoc/issues/104.
Parent issue: https://github.com/joffrey-bion/livedoc/issues/106

**Closed as completed by joffrey-bion** 2018-05-04 19:23 UTC
Labels: duplicate
